apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aix-production
resources:
  - ../base
nameSuffix: -production
images:
  - name: ghcr.io/example/aix-open
    newTag: replace-with-release-tag
  - name: ghcr.io/example/aix-web
    newTag: replace-with-release-tag
